using System;
using System.Collections.Generic;

namespace ContinuousRunner
{
    public interface IExecutionResult
    {
        /// <summary>
        /// The overall status of whether the work succeeded or failed
        /// </summary>
        Status Status { get; }

        /// <summary>
        /// Any log output generated by running this work
        /// </summary>
        IList<Tuple<DateTime, Severity, string>> Logs { get; }
    }
}
