using System;
using System.Collections.Generic;

namespace Contestual
{
    public class TestResult
    {
        /// <summary>
        /// The overall status of whether the test succeeded or failed
        /// </summary>
        /// <value>The status.</value>
        public TestStatus Status { get; private set; }

        /// <summary>
        /// Any log output generated by running this test
        /// </summary>
        /// <value>The logs.</value>
        public IList<string> Logs { get; private set; }
    }
}

